Sablanca/Sablanca/Controllers/CategoryController.cs
using Sablanca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Sablanca.Controllers
{
    public class CategoryController : Controller
    {
        SablancaDB db = new SablancaDB();
        // GET: Category
        public ActionResult Detail(int id, string order, decimal? fromPrice, decimal? toPrice, int? page)
        {
            if (id == null)
            {
                return Redirect("/NotFound/Index");
            }
            var category = db.Categories.Find(id);
            if (category == null)
            {
                return Redirect("/NotFound/Index");
            }

            var products = db.Products.Where(p => p.category_id == id).OrderByDescending(p => p.product_id);

            if (order != null)
                switch (order)
                {
                    case "desc":
                        products = products.OrderByDescending(p => p.product_price);
                        ViewBag.order = "desc";
                        break;
                    case "asc":
                        products = products.OrderBy(p => p.product_price);
                        ViewBag.order = "asc";
                        break;
                    default:
                        ViewBag.order = "default";
                        break;
                }

            if (fromPrice != null)
            {
                ViewBag.from = fromPrice;
                products = (IOrderedQueryable<Product>)products.Where(p => p.product_price >= fromPrice);
            }

            if (toPrice != null)
            {
                ViewBag.to = toPrice;
                products = (IOrderedQueryable<Product>)products.Where(p => p.product_price <= toPrice);
            }

            int pageNumber = (page ?? 1);
            ViewBag.Category = category.category_name;

            return View(products.ToPagedList(pageNumber, 8));
        }
    }
}

Sablanca/Sablanca/Controllers/ProfileController.cs
using Sablanca.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sablanca.Controllers
{
    public class ProfileController : ProtectController
    {
        SablancaDB db = new SablancaDB();
        // GET: Profile
        public ActionResult Index()
        {
            User oldUser = Session["user"] as User;
            User newUser = db.Users.Where(us => us.email.Equals(oldUser.email)).FirstOrDefault();
            Session["user"] = newUser;
            var errMsg = TempData["ErrorMessage"] as string;
            ViewBag.Infor = errMsg;
            return View(newUser);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(FormCollection frm)
        {
            string fullname = frm["full_name"];
            string phone = frm["phone_number"];
            string email = frm["email"];
            string address = frm["address"];

            User user = db.Users.Where(us => us.email == email).SingleOrDefault();
            user.full_name = fullname;
            user.phone_number = phone;
            user.address = address;
            if (user != null)
            {
                db.Entry(user).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                ViewBag.Information = "Cập nhật thành công";
            }
            else
            {
                ViewBag.Information = "Có lỗi xảy ra khi cập nhật";
            }

            return View("Index", user);
        }

        public ActionResult ChangePass()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChangePass(FormCollection frm)
        {
            if (ModelState.IsValid)
            {
                User user = Session["user"] as User;
                string old_password = frm["old_password"];
                string new_password = frm["password"];
                string confirm_password = frm["confirm_password"];
                if (!Helper.EncodePassword(old_password).Equals(user.password))
                {
                    ViewBag.Error = "Mật khẩu cũ không đúng!";
                    return View(frm);
                }
                User userEntity = db.Users.Where(us => us.email == user.email).SingleOrDefault();
                userEntity.password = Helper.EncodePassword(new_password);
                db.Entry(userEntity).State = EntityState.Modified;
                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                ViewBag.Information = "Đổi mật khẩu thành công";

                return View("Index", userEntity);

            }
            ViewBag.Error = "Chưa validate!";
            return View();
        }

        [NotAuthorize]
        public ActionResult Logout()
        {
            Session["user"] = null;
            return Redirect("/");
        }
        [NotAuthorize]
        public ActionResult Login()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [NotAuthorize]
        public ActionResult Login(FormCollection frm)
        {
            if (ModelState.IsValid)
            {
                string email = frm["email"];
                string password = frm["password"];

                string currentPass = Helper.EncodePassword(password);
                var user = db.Users.Where(s => s.email.Equals(email) && s.password.Equals(currentPass)).SingleOrDefault();
                if (user != null && !user.is_active)
                {
                    ViewBag.error = "Tài khoản của bạn đã bị khoá";
                    return View();
                }
                else if (user != null && user.is_active)
                {
                    //add session
                    Session["user"] = user;
                    return Redirect("/");
                }
                else
                {
                    ViewBag.error = "Đăng nhập thất bại";
                    return View();
                }
            }
            ViewBag.error = "Đăng nhập thất bại";
            return View();
        }
        [NotAuthorize]
        public ActionResult Register()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return Redirect("/");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [NotAuthorize]
        public ActionResult Register(FormCollection frm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string full_name = frm["full_name"];
                    string email = frm["email"];
                    string password = frm["password"];
                    string confirm_password = frm["confirm_password"];
                    string phone = frm["phone_number"];
                    string address = frm["address"];

                    if (!password.Equals(confirm_password))
                    {
                        ViewBag.Error = "Mật khẩu không khớp.";
                        return View();
                    }

                    var user = db.Users.Where(us => us.email == email).SingleOrDefault();

                    if (user != null)
                    {
                        ViewBag.Error = "Vui lòng nhập địa chỉ email khác.";
                        return View();
                    }

                    User u = new User();
                    u.full_name = full_name;
                    u.email = email;
                    u.password = Helper.EncodePassword(password);
                    u.address = address;
                    u.phone_number = phone;
                    u.role = 0;
                    u.is_active = true;
                    db.Configuration.ValidateOnSaveEnabled = false;
                    db.Users.Add(u);
                    db.SaveChanges();
                }
                return Redirect("/Profile/Login");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi dữ liệu " + ex;
                return View();
            }
        }
    }
}

Sablanca/Sablanca/Views/Shared/_BreadcrumbLevelOne.cshtml
@model Sablanca.Models.DanhMuc

<section class="inner-section single-banner">
    <div class="container">
        <h2>@Model.DanhMuc.TenDM</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page">
                @Model.DanhMuc.TenDM
            </li>
        </ol>
    </div>
</section>

Sablanca/Sablanca/Views/Shared/_BreadcrumbLevelTwo.cshtml
@model Sablanca.Models.SanPham

<section class="single-banner inner-section">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                <li class="breadcrumb-item"><a href="#">@Model.DanhMuc.TenDM</a></li>
                <li class="breadcrumb-item active" aria-current="page">@Model.TenSP</li>
            </ol>
        </nav>
    </div>
</section>

Sablanca/Sablanca/Views/Shared/_Header.cshtml
<section class="header-part">
    <div class="container">
        <div class="header-content">
            <div class="header-media-group">
                <button class="header-user">
                    <img src="~/wwwroot/images/user.png" alt="user" />
                </button><a href="@Url.Action("Index","Home")">

                    <img src=""
                         alt="logo" />
                </a><button class="header-src"><i class="fas fa-search"></i></button>
            </div>
            <a href="@Url.Action("Index","Home")" class="header-logo">
                <img src="~/wwwroot/images/logo_sab.png"
                     alt="logo" />
            </a>

            @if (Session["HoTen"] == null)
            {
                <a href="@Url.Action("Index","Taikhoans")" class="header-widget" title="My Account">
                    <img src="~/wwwroot/images/user.png" alt="user"><span>Đăng nhập</span>
                </a>
            }
            else
            {
                <a href="@Url.Action("Edit","TaiKhoans", new { id=Session["idUser"] })" class="header-widget" title="My Account">
                    <img src="~/wwwroot/images/user.png" alt="user"><span>@Session["HoTen"]</span>
                </a>
                <div style="background-color:#c3654b; padding: 2px 5px;border-radius:5px; margin-left:5px">
                    <a href="@Url.Action("Logout","TaiKhoans")" style="color:#FFF;font-size:14px">
                        Thoát
                    </a>
                </div>
            }




            <form class="header-form">
                <input type="text" placeholder="Tìm kiếm..." /><button>
                    <i class="fas footer-social"></i>
                </button>
            </form>
            <div class="header-widget-group">
                <a class="header-widget header-cart"
                   title="Cartlist"
                   href="@Url.Action("Checkout","Home")">
                    <i class="fas fa-shopping-basket"></i><sup>2</sup><span>Tổng<small>1.220.000đ</small></span>
                </a>
            </div>
        </div>
    </div>
</section>

Sablanca/Sablanca/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8" />

<head>
    <meta charset="UTF-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="author" content="mironcoder" />
    <meta name="email" content="mironcoder@gmail.com" />
    <meta name="profile" content="https://themeforest.net/user/mironcoder" />
    <meta name="template" content="Organe" />
    <meta name="title" content="Sablanca - Phong cách thời trang theo xu hướng quốc tế" />
    <meta name="keywords" content="giày dép nữ thời trang, túi xách nữ thời trang, ví nữ thời trang, ba lô nữ thời trang" />
    <title>@ViewBag.Title - Sablanca</title>
    <link rel="icon" href="~/wwwroot/images/favicon.ico" />
    <link rel="stylesheet" href="~/wwwroot/fonts/flaticon/flaticon.css" />
    <link rel="stylesheet" href="~/wwwroot/fonts/icofont/icofont.min.css" />
    <link rel="stylesheet" href="~/wwwroot/fonts/fontawesome/fontawesome.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/nice-select.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/venobox.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/slick.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/bootstrap.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/custom/main.css" />
    <link rel="stylesheet" href="~/wwwroot/css/custom/index.css" />

    @RenderSection("addcss", required: false)
</head>

<body>
    <section class="user-form-part">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-5">
                    <div class="user-form-logo">
                        <a href="index.html">
                            <img src="~/wwwroot/images/logo_sab.png"
                                 alt="logo" />
                        </a>
                    </div>
                    <div class="user-form-card">
                        <div class="user-form-title">
                            <h2>@RenderSection("title", required: true)</h2>
                            <p>@RenderSection("subtitle", required: true)</p>
                        </div>
                        @RenderBody()
                    </div>
                    <div class="user-form-footer">
                        <p>&copy; Bản quyền thuộc về nhóm 14</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="~/wwwroot/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/wwwroot/js/vendor/popper.min.js"></script>
    <script src="~/wwwroot/js/vendor/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
<!-- Mirrored from mironmahmud.com/organe/assets/ltr/change-password.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 15 Jun 2021 14:24:42 GMT -->

</html>

Sablanca/Sablanca/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=utf-8" />

<head>
    <meta charset="UTF-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="author" content="mironcoder" />
    <meta name="email" content="mironcoder@gmail.com" />
    <meta name="profile" content="https://themeforest.net/user/mironcoder" />
    <meta name="template" content="Organe" />
    <meta name="title" content="Sablanca - Phong cách thời trang theo xu hướng quốc tế" />
    <meta name="keywords" content="giày dép nữ thời trang, túi xách nữ thời trang, ví nữ thời trang, ba lô nữ thời trang" />
    <title>Sablanca - Phong cách thời trang theo xu hướng quốc tế</title>
    <link rel="icon" href="~/wwwroot/images/favicon.ico" />
    <link rel="stylesheet" href="~/wwwroot/fonts/flaticon/flaticon.css" />
    <link rel="stylesheet" href="~/wwwroot/fonts/icofont/icofont.min.css" />
    <link rel="stylesheet" href="~/wwwroot/fonts/fontawesome/fontawesome.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/nice-select.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/venobox.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/slick.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/vendor/bootstrap.min.css" />
    <link rel="stylesheet" href="~/wwwroot/css/custom/main.css" />
    <link rel="stylesheet" href="~/wwwroot/css/custom/index.css" />
</head>

<body>
    <div class="backdrop"></div>
    @{ 
        Html.RenderAction("_Header","Home");
     }
    <!-- Start menu pc -->
    @{ 
        Html.RenderAction("_MenuPC","Home");
     }
    <!-- End menu pc -->

    @RenderBody()
    <section class="intro-part">
        <div class="container">
            <div class="row intro-content">
                <div class="col-sm-6 col-lg-3">
                    <div class="intro-wrap">
                        <div class="intro-icon"><i class="fas fa-truck"></i></div>
                        <div class="intro-content">
                            <h5>miễn phí giao hàng</h5>
                            <p>
                                Cho đơn hàng từ 200.000 trở lên. (Áp dụng nội thành Hồ Chí Minh)
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="intro-wrap">
                        <div class="intro-icon"><i class="fas fa-sync-alt"></i></div>
                        <div class="intro-content">
                            <h5>Hoàn tiền 100%</h5>
                            <p>Đổi trả hoàn tiền 100% không cần lý do</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="intro-wrap">
                        <div class="intro-icon"><i class="fas fa-headset"></i></div>
                        <div class="intro-content">
                            <h5>hỗ trợ 24/7</h5>
                            <p>Đội ngũ hỗ trợ giải quyết vấn đề 24/7</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="intro-wrap">
                        <div class="intro-icon"><i class="fas fa-lock"></i></div>
                        <div class="intro-content">
                            <h5>Thanh toán nhanh</h5>
                            <p>Hỗ trợ các phương thức thanh toán an toàn</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer-part">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-xl-3">
                    <div class="footer-widget">
                        <a class="footer-logo" href="#">
                            <img src="~/wwwroot/images/logo_sab.png"
                                 alt="logo" />
                        </a>
                        <p class="footer-desc">
                            Sablanca là công ty sản xuất, kinh doanh chuỗi cửa hàng thời trang cao cấp về túi xách, ví, ba lô,… dành cho phái nữ
                        </p>
                        <ul class="footer-social">
                            <li><a class="icofont-facebook" href="https://www.facebook.com/Sablanca.vn"></a></li>
                            <li><a class="icofont-twitter" href="#"></a></li>
                            <li><a class="icofont-linkedin" href="#"></a></li>
                            <li><a class="icofont-instagram" href="https://www.instagram.com/sablanca.vn/"></a></li>
                            <li><a class="icofont-pinterest" href="#"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="footer-widget contact">
                        <h3 class="footer-title">liên hệ</h3>
                        <ul class="footer-contact">
                            <li>
                                <i class="icofont-ui-email"></i>
                                <p>
                                    <span>contact@sablanca.vn</span>
                                </p>
                            </li>
                            <li>
                                <i class="icofont-ui-touch-phone"></i>
                                <p>
                                    <span>1800 6050</span>
                                </p>
                            </li>
                            <li>
                                <i class="icofont-location-pin"></i>
                                <p>Trụ sở chính: 248C Phan Đình Phùng, P1, Q.Phú Nhuận, HCM.</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="footer-widget">
                        <h3 class="footer-title">hướng dẫn & hỗ trợ</h3>
                        <div class="footer-links">
                            <ul>
                                <li><a href="#">FAQs</a></li>
                                <li><a href="#">Hướng dẫn mua hàng</a></li>
                                <li><a href="#">Chính sách đổi trả</a></li>
                                <li><a href="#">Giới thiệu</a></li>
                                <li><a href="#">Hệ thống 23 cửa hàng</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-3">
                    <div class="footer-widget">
                        <h3 class="footer-title">Download App</h3>
                        <p class="footer-desc">
                            Ứng dụng Sablanca đã có trên Google Play & App Store. Tải ứng
                            dụng ngay!
                        </p>
                        <div class="footer-app">
                            <a href="#"><img src="~/wwwroot/images/google-store.png" alt="google" /></a><a href="#"><img src="~/wwwroot/images/app-store.png" alt="app" /></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="footer-bottom">
                        <p class="footer-copytext">
                            &copy; Bản quyền thuộc về Nhóm 14
                        </p>
                        <div class="footer-card">
                            <a href="#"><img src="~/wwwroot/images/payment/jpg/01.jpg" alt="payment" /></a><a href="#"><img src="~/wwwroot/images/payment/jpg/02.jpg" alt="payment" /></a><a href="#"><img src="~/wwwroot/images/payment/jpg/03.jpg" alt="payment" /></a><a href="#">
                                <img src="~/wwwroot/images/payment/jpg/04.jpg" alt="payment" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/wwwroot/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/wwwroot/js/vendor/popper.min.js"></script>
    <script src="~/wwwroot/js/vendor/bootstrap.min.js"></script>
    <script src="~/wwwroot/js/vendor/nice-select.min.js"></script>
    <script src="~/wwwroot/js/vendor/venobox.min.js"></script>
    <script src="~/wwwroot/js/vendor/countdown.min.js"></script>
    <script src="~/wwwroot/js/vendor/slick.min.js"></script>
    <script src="~/wwwroot/js/custom/nice-select.js"></script>
    <script src="~/wwwroot/js/custom/countdown.js"></script>
    <script src="~/wwwroot/js/custom/accordion.js"></script>
    <script src="~/wwwroot/js/custom/venobox.js"></script>
    <script src="~/wwwroot/js/custom/slick.js"></script>
    <script src="~/wwwroot/js/custom/main.js"></script>
</body>
<!-- Mirrored from mironmahmud.com/organe/assets/ltr/profile.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 15 Jun 2021 14:24:36 GMT -->
</html>

Sablanca/Sablanca/Views/Shared/_ListOrder.cshtml
@model IEnumerable<Sablanca.Models.Custom_order>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="account-card">
                <div class="account-title">
                    <h4>Lịch sử mua hàng</h4>
                </div>
                <div class="table-scroll">
                    @if (Model != null)
                    {
                        <table class="table-list">
                            <thead>
                                <tr>
                                    <th scope="col">Mã đơn</th>
                                    <th scope="col">Tổng tiền</th>
                                    <th scope="col">Ngày tạo</th>
                                    <th scope="col">Trạng thái</th>
                                    <th scope="col">Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="table-serial">
                                            <h6>@item.order_id</h6>
                                        </td>
                                        <td class="table-name">
                                            <h6>@string.Format("{0:#,##}", item.amount) vnđ</h6>
                                        </td>
                                        <td class="table-brand">
                                            <h6>@item.created_at</h6>
                                        </td>
                                        <td class="table-quantity">
                                            <h6>@item.status</h6>
                                        </td>
                                        <td class="table-action">
                                            <a class="view" href="/Invoice/Index/@item.order_id">
                                                <i class="fas fa-eye"></i> <span style="color: #198754">Chi tiết</span>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                    else
                    {
                        <h1 class="text-center">Chưa có đơn hàng</h1>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Sablanca/Sablanca/Views/Shared/_MenuMobile.cshtml
@model IEnumerable<Sablanca.Models.Category>

<aside class="nav-sidebar">
    <div class="nav-header">
        <a href="#"><img src="~/wwwroot/images/logo_sab.png" alt="logo" /></a><button class="nav-close">
            <i class="icofont-close"></i>
        </button>
    </div>
    <div class="nav-content">
        <div class="nav-btn">
            @if (ViewBag.User == null)
            {
                <a href="@Url.Action("Login","Profile")" class="btn btn-inline"><i class="fa fa-unlock-alt"></i><span>Đăng nhập</span></a>
            }
            else
            {
                <a href="@Url.Action("Index","Profile")" class="btn btn-inline"><span>@ViewBag.User</span></a>
            }

        </div>
        <ul class="nav-list">
            <li>
                <a class="nav-link" href="#"><i class="icofont-home"></i>Trang chủ</a>
            </li>
            <li>
                <a class="nav-link dropdown-link" href="#"><i class="icofont-page"></i>Danh mục sản phẩm</a>
                <ul class="dropdown-list">
                    @foreach (var item in Model)
                    {
                        <li><a href="@Url.Action("Detail","Category", new { id = item.category_id })">@item.category_name</a></li>
                    }
                </ul>
            </li>
            <li>
                <a class="nav-link cart-btn" href="/Checkout">
                    <i class="fas fa-shopping-basket"></i><span>Giỏ hàng</span><sup>9+</sup>
                </a>
            </li>
            <li>
                <a class="nav-link" href="contact.html"><i class="icofont-contacts"></i>Liên hệ</a>
            </li>
            <li>
                <a class="nav-link" href="@Url.Action("Login","Profile")"><i class="icofont-logout"></i>Đăng xuất</a>
            </li>
        </ul>
        <div class="nav-info-group">
            <div class="nav-info">
                <i class="icofont-ui-touch-phone"></i>
                <p><small>Liên hệ</small><span>1800 6050</span></p>
            </div>
            <div class="nav-info">
                <i class="icofont-ui-email"></i>
                <p><small>Email</small><span>contact@sablanca.vn</span></p>
            </div>
        </div>
        <div class="nav-footer">
            <p>Bản quyền thuộc về nhóm 14</p>
        </div>
    </div>
</aside>

Sablanca/Sablanca/Views/Shared/_MenuPC.cshtml
@model IEnumerable<Sablanca.Models.DanhMuc>
<nav class="navbar-part">
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="navbar-content">
                <ul class="navbar-list">
                    <li class="navbar-item dropdown">
                        <a class="navbar-link" href="@Url.Action("Index","Home")">trang chủ</a>
                    </li>
                    <li class="navbar-item dropdown">
                        <a class="navbar-link dropdown-arrow" href="#">danh mục sản phẩm</a>
                        <ul class="dropdown-position-list">
                            @foreach (var item in Model)
                            {
                                <li><a href="@Url.Action("ViewProductByCategory","Home", new { maDanhMuc = item.MaDM })">@item.TenDM</a></li>
                            }

                        </ul>
                    </li>
                    <li class="navbar-item dropdown">
                        <a class="navbar-link" href="#">khuyến mãi</a>
                    </li>
                    <li class="navbar-item dropdown">
                        <a class="navbar-link" href="#">hệ thống cửa hàng</a>
                    </li>
                </ul>
                <div class="navbar-info-group">
                    <div class="navbar-info">
                        <i class="icofont-ui-touch-phone"></i>
                        <p><small>hotline</small><span>1800 6050</span></p>
                    </div>
                    <div class="navbar-info">
                        <i class="icofont-ui-email"></i>
                        <p>
                            <small>email</small><span>contact@sablanca.vn</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</nav>