Sablanca/Sablanca/Areas/Admin/Controllers/DanhMucsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sablanca.Models;

namespace Sablanca.Areas.Admin.Controllers
{
    public class DanhMucsController : Controller
    {
        private SablancaDB db = new SablancaDB();

        // GET: Admin/DanhMucs
        public ActionResult Index()
        {
            return View(db.DanhMucs.ToList());
        }

        // GET: Admin/DanhMucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/DanhMucs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDM,TenDM,MoTa")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.DanhMucs.Add(danhMuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(danhMuc);
        }

        // GET: Admin/DanhMucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDM,TenDM,MoTa")] DanhMuc danhMuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(danhMuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", "MoTa");
            return View(danhMuc);

            /*if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDdanhmuc = new SelectList(db.DanhMucSanPhams, "IDdanhmuc", "Tendanhmuc", sanPham.IDdanhmuc);
            return View(sanPham);*/
        }

        // GET: Admin/DanhMucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            if (danhMuc == null)
            {
                return HttpNotFound();
            }
            return View(danhMuc);
        }

        // POST: Admin/DanhMucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DanhMuc danhMuc = db.DanhMucs.Find(id);
            db.DanhMucs.Remove(danhMuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sablanca/Sablanca/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sablanca.Models;

namespace Sablanca.Areas.Admin.Controllers
{
    public class SanPhamsController : Controller
    {
        SablancaDB db = new SablancaDB();

        // GET: Admin/SanPhams
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.DanhMuc);
            return View(sanPhams.ToList());
        }

        // GET: Admin/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM");
            return View();
        }

        // POST: Admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,MaDM,TenSP,GiaBan,GiaGoc,MauSac,ChatLieu,LoaiDayDeo,KichThuoc,Dong,MoTaSP,AnhSP")] SanPham sanPham)
        {
            
                /*if (ModelState.IsValid)
                {
                    sanPham.AnhSP = "";
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/wwwroot/AnhSP/" + FileName);
                        f.SaveAs(UploadPath);
                        sanPham.AnhSP = FileName;
                    }
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    return RedirectToAction("Index");
            }
                
           
               
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                ViewBag.Error = "Dữ liệu không hợp lệ!";
                return View(sanPham);*/
            if (ModelState.IsValid)
            {
                sanPham.AnhSP = "";
                var f = Request.Files["ImageFile"];

                if (f != null && f.ContentLength > 0)
                {
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    //lấy tên file upload
                    string UploadPath = Server.MapPath("~/wwwroot/AnhSP/" + FileName);
                    //Copy và lưu file vào server.
                    f.SaveAs(UploadPath);
                    //Lưu tên file vào trường Image
                    sanPham.AnhSP = FileName;
                }
                else
                {
                    ViewBag.Error = "Chưa nhập ảnh ";
                    return View("Create");
                }


                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }



            ViewBag.Error = "Lỗi nhập dữ liệu! ";
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
            return View(sanPham);

            /*if (ModelState.IsValid)
            {
                sanPham.AnhSP = "";
                var f = Request.Files["ImageFile"]; 
                if (f != null && f.ContentLength > 0)
                {
                    //Use  Namespace  called  :	System.IO
                    string FileName = System.IO.Path.GetFileName(f.FileName);
                    //Lấy  tên  file  upload
                    string UploadPath = Server.MapPath("~/wwwroot/AnhSP/" + FileName);
                    //Copy  Và  lưu  file  vào  server.
                    f.SaveAs(UploadPath);
                    //Lưu  tên  file  vào  trường  Image
                    sanPham.AnhSP  =  FileName;
                }

                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                *//*return RedirectToAction("Index");*/


            /*ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
            return View(sanPham);*/

        }

        // GET: Admin/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,MaDM,TenSP,GiaBan,GiaGoc,MauSac,ChatLieu,LoaiDayDeo,KichThuoc,Dong,MoTaSP,AnhSP")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f.FileName);
                        string UploadPath = Server.MapPath("~/wwwroot/AnhSP/" + FileName);
                        f.SaveAs(UploadPath);
                        sanPham.AnhSP = FileName;
                    }
                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Dữ liệu không hợp lệ!"+ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                return View(sanPham);
            }
            /*if (ModelState.IsValid)
                {
                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.MaDM = new SelectList(db.DanhMucs, "MaDM", "TenDM", sanPham.MaDM);
                return View(sanPham);
            }*/

            /*// GET: Admin/SanPhams/Delete/5
            public ActionResult Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SanPham sanPham = db.SanPhams.Find(id);
                if (sanPham == null)
                {
                    return HttpNotFound();
                }
                return View(sanPham);
            }

            // POST: Admin/SanPhams/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public ActionResult DeleteConfirmed(int id)
            {
                SanPham sanPham = db.SanPhams.Find(id);
                db.SanPhams.Remove(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }*/
        }
        /*[HttpPost]
        public JsonResult Delete(int? id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            try
            {
                db.SanPhams.Remove(sanPham);
                db.SaveChanges();
                bool success = true;

                return Json(success, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                bool success = false;
                return Json(success, JsonRequestBehavior.AllowGet);
            }

        }*/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Sablanca/Sablanca/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
=ơ;<!DOCTYPE html>
<link href="~/Areas/Admin/assets/css/admin.css" rel="stylesheet" />
<html lang="en">
<!-- Mirrored from truelysell-admin.dreamguystech.com/template/dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 21 Jun 2021 14:21:50 GMT -->
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=0" />
    <title>Trang quản trị</title>

    <!-- Favicons -->
    <link rel="shortcut icon" href="~/wwwroot/images/favicon.ico" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
          href="~/Areas/Admin/assets/plugins/bootstrap/css/bootstrap.min.css" />

    <!-- Fontawesome CSS -->
    <link rel="stylesheet"
          href="~/Areas/Admin/assets/plugins/fontawesome/css/fontawesome.min.css" />
    <link rel="stylesheet" href="~/Areas/Admin/assets/plugins/fontawesome/css/all.min.css" />

    <!-- Animate CSS -->
    <link rel="stylesheet" href="~/Areas/Admin/assets/css/animate.min.css" />

    <!-- Main CSS -->
    <link rel="stylesheet" href="~/Areas/Admin/assets/css/admin.css" />
</head>

<body>
    <div class="main-wrapper">
        <!-- Header -->
        <div class="header">
            <div class="header-left">
                <a href="@Url.Action("Dashboard","Home")" class="logo logo-small">
                    <img src="~/Areas/Admin/assets/img/logo-icon.png"
                         alt="Logo"
                         width="30"
                         height="30" />
                </a>
            </div>
            <a href="javascript:void(0);" id="toggle_btn">
                <i class="fas fa-align-left"></i>
            </a>
            <a class="mobile_btn" id="mobile_btn" href="javascript:void(0);">
                <i class="fas fa-align-left"></i>
            </a>

            <ul class="nav user-menu">
                <!-- User Menu -->
                <li class="nav-item dropdown">
                    <a href="javascript:void(0)"
                       class="dropdown-toggle user-link nav-link"
                       data-toggle="dropdown">
                        <span class="user-img">
                            <img class="rounded-circle"
                                 src="~/Areas/Admin/assets/img/user.jpg"
                                 width="40"
                                 alt="Admin" />
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="@Url.Action("Index","Home")">Đăng xuất</a>
                    </div>
                </li>
                <!-- /User Menu -->
            </ul>
        </div>
        <!-- /Header -->
        <!-- Sidebar -->
        <div class="sidebar" id="sidebar">
            <div class="sidebar-logo">
                <a href="@Url.Action("Dashboard","Home")">
                    <img src="~/wwwroot/images/logo_sab.png"
                         class="img-fluid"
                         alt="" />
                </a>
            </div>
            <div class="sidebar-inner slimscroll">
                <div id="sidebar-menu" class="sidebar-menu">
                    <ul>
                        <li class="active">
                            <a href="@Url.Action("Dashboard","Home")"><i class="fas fa-columns"></i> <span>Dashboard</span></a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","DanhMucs")">
                                <i class="fas fa-layer-group"></i>
                                <span>Quản lý danh mục</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","SanPhams")">
                                <i class="fab fa-buffer"></i>
                                <span>Quản lý sản phẩm</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Manage_order","Home")">
                                <i class="fas fa-shopping-cart"></i>
                                <span>Quản lý đơn hàng</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","TaiKhoans")"><i class="fas fa-user"></i> <span>Quản lý tài khoản</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Sidebar -->

        <div class="page-wrapper">
            @RenderBody()
        </div>
    </div>

    <!-- jQuery -->
    <script src="~/Areas/Admin/assets/js/jquery-3.5.0.min.js"></script>

    <!-- Bootstrap Core JS -->
    <script src="~/Areas/Admin/assets/js/popper.min.js"></script>
    <script src="~/Areas/Admin/assets/plugins/bootstrap/js/bootstrap.min.js"></script>

    <!-- Slimscroll JS -->
    <script src="~/Areas/Admin/assets/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom JS -->
    <script src="~/Areas/Admin/assets/js/admin.js"></script>
</body>

<!-- Mirrored from truelysell-admin.dreamguystech.com/template/dashboard.html by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 21 Jun 2021 14:22:07 GMT -->
</html>